spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/fontend}
  security:
    jwt:
      secret: 4U+r5vbV3F85zFasrgxhVlVH802OOx/mJaF2JMN5ZaQ=
      expiration: 86400000 # 24h
      refresh-expiration: 604800000 # 7 days
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 5f058ebce5f72c
    password: dd8665af306128

logging:
  level:
    com.fontend: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
